"""FastAPI routes for the super-brain payments surface.

Endpoints:

    POST /api/stripe/webhook
        Verify Stripe signature → record revenue event → deliver playbook PDF.

    POST /webhook/stripe
        Alias at the root-level path that some Stripe dashboard configs prefer.

Delivery fires in the background (``BackgroundTasks``) so Stripe always gets
a fast 200 and never retries due to email/R2 latency.
"""
from __future__ import annotations

import json
import logging
from types import SimpleNamespace

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException, Request, Response

from ...web.dependencies import get_storage
from .stripe_client import parse_event_for_revenue, verify_webhook_signature
from .revenue_events import record_event

logger = logging.getLogger(__name__)

router = APIRouter()


def _handle_webhook_body(payload: bytes, sig_header: str):
    """Shared verification + parsing logic. Returns (event_dict, error_response)."""
    ok, reason = verify_webhook_signature(payload, sig_header)
    if not ok:
        logger.warning("stripe webhook rejected: %s", reason)
        return None, (400, "invalid_signature")

    try:
        event = json.loads(payload.decode("utf-8"))
    except Exception as exc:
        logger.warning("stripe webhook: bad json: %s", exc)
        return None, (400, "bad_json")

    return event, None


@router.post("/stripe/webhook")
@router.post("/webhook/stripe")  # alias for Stripe dashboard flexibility
async def stripe_webhook(
    request: Request,
    background_tasks: BackgroundTasks,
    storage=Depends(get_storage),
):
    """Receive a Stripe event, verify signature, record revenue, deliver PDF.

    Idempotent: Stripe retries the same ``event.id`` on non-2xx, and
    ``record_event`` deduplicates on the same id.
    """
    payload    = await request.body()
    sig_header = request.headers.get("stripe-signature", "")

    event, err = _handle_webhook_body(payload, sig_header)
    if err:
        raise HTTPException(status_code=err[0], detail=err[1])

    revenue_args = parse_event_for_revenue(event)
    if revenue_args is None:
        return {"status": "ignored", "type": event.get("type", "unknown")}

    # Record the revenue event (idempotent)
    server_shim = SimpleNamespace(storage=storage)
    result = await record_event(server_shim, revenue_args)

    # Fire-and-forget PDF delivery for completed checkout sessions
    if event.get("type") == "checkout.session.completed":
        session   = (event.get("data") or {}).get("object") or {}
        to_email  = (session.get("customer_details") or {}).get("email")
        if not to_email:
            to_email = session.get("customer_email")
        if to_email:
            from .delivery import deliver_playbook
            background_tasks.add_task(deliver_playbook, to_email)
            logger.info("stripe webhook: queued delivery to %s", to_email)
        else:
            logger.warning("stripe webhook: checkout.session.completed but no email in session %s",
                           session.get("id"))

    return {"status": "ok", **result}


@router.get("/playbook/download/{token}")
async def playbook_download(token: str):
    """Serve the playbook PDF to a customer via a time-limited signed token.

    The token is generated by ``delivery.generate_relay_url`` and verified
    with HMAC-SHA256 signed by ``STRIPE_WEBHOOK_SECRET``.
    """
    from .delivery import verify_relay_token, fetch_pdf_from_r2

    email = verify_relay_token(token)
    if email is None:
        raise HTTPException(status_code=403, detail="invalid_or_expired_token")

    try:
        pdf_bytes = await fetch_pdf_from_r2()
    except Exception as exc:
        logger.error("playbook download: R2 fetch failed for %s: %s", email, exc)
        raise HTTPException(status_code=503, detail="download_unavailable")

    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": "attachment; filename=playbook.pdf"},
    )
